compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  '@nx/jest@*':
    peerDependenciesMeta:
      nx:
        optional: true
  '@nx/js@*':
    peerDependenciesMeta:
      nx:
        optional: true
  jest-cli@*:
    dependencies:
      '@jest/console': '*'
      '@jest/reporters': '*'
  jest-config@*:
    dependencies:
      jest-runtime: '*'
      ts-node: '*'
    peerDependenciesMeta:
      typescript:
        optional: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.1.1.cjs
